# Generated by Django 6.0.4 on 2026-04-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='plants/')),
                ('category', models.CharField(choices=[('TREE', 'Tree'), ('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('FLOWER', 'Flower'), ('HERB', 'Herb')], max_length=20)),
                ('is_edible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
